
	var kWvsBaselineG = new jGauge(); // Create a new jGauge.
				kWvsBaselineG.id = 'kWvsBaseline'; // Link the new jGauge to the placeholder DIV.
				kWvsBaselineG.autoPrefix = autoPrefix.si; // Use SI prefixing (i.e. 1k = 1000).
				kWvsBaselineG.imagePath = '/site-media/jgauge/img/jgauge_face_taco_transparentMod.png';
				kWvsBaselineG.segmentStart = -225;
				kWvsBaselineG.segmentEnd = 45;
				kWvsBaselineG.width = 170;
				kWvsBaselineG.height = 170;
				kWvsBaselineG.needle.imagePath = '/site-media/jgauge/img/jgauge_needle_taco.png';
				kWvsBaselineG.needle.xOffset = 0;
				kWvsBaselineG.needle.yOffset = 0;
                                kWvsBaselineG.label.yOffset = 55;
                                kWvsBaselineG.label.color = '#FFFFFF';
                                kWvsBaselineG.label.precision = 0; // 0 decimals (whole numbers).
				kWvsBaselineG.label.suffix = '%'; // Make the value label watts.
				kWvsBaselineG.ticks.labelRadius = 45;
                                kWvsBaselineG.ticks.labelColor = '#0ce';
                                kWvsBaselineG.ticks.start = -45;
                                kWvsBaselineG.ticks.end = 45;
                                kWvsBaselineG.ticks.count = 5;
                                kWvsBaselineG.ticks.color = 'rgba(0, 0, 0, 0)';
                                kWvsBaselineG.range.color = 'rgba(0, 0, 0, 0)';
var gaugeTwo = new jGauge(); // Create a new jGauge.
				gaugeTwo.id = 'gaugeTwo'; // Link the new jGauge to the placeholder DIV.
				gaugeTwo.autoPrefix = autoPrefix.si; // Use SI prefixing (i.e. 1k = 1000).
				gaugeTwo.imagePath = '/site-media/jgauge/img/jgauge_face_taco_transparentMod.png';
				gaugeTwo.segmentStart = -225;
				gaugeTwo.segmentEnd = 45;
				gaugeTwo.width = 170;
				gaugeTwo.height = 170;
				gaugeTwo.needle.imagePath = '/site-media/jgauge/img/jgauge_needle_taco.png';
				gaugeTwo.needle.xOffset = 0;
				gaugeTwo.needle.yOffset = 0;
                                gaugeTwo.label.yOffset = 55;
                                gaugeTwo.label.color = '#FFFFFF';
                                gaugeTwo.label.precision = 3; // 0 decimals (whole numbers).
				gaugeTwo.label.suffix = '%'; // Make the value label watts.
				gaugeTwo.ticks.labelRadius = 45;
                                gaugeTwo.ticks.labelColor = '#0ce';
                                gaugeTwo.ticks.start = 0;
                                gaugeTwo.ticks.end = 3;
                                gaugeTwo.ticks.count = 5;
                                gaugeTwo.ticks.color = 'rgba(0, 0, 0, 0)';
                                gaugeTwo.range.color = 'rgba(0, 0, 0, 0)';
var gaugeThree = new jGauge(); // Create a new jGauge.
				gaugeThree.id = 'gaugeThree'; // Link the new jGauge to the placeholder DIV.
				gaugeThree.autoPrefix = autoPrefix.si; // Use SI prefixing (i.e. 1k = 1000).
				gaugeThree.imagePath = '/site-media/jgauge/img/jgauge_face_taco_transparentMod.png';
				gaugeThree.segmentStart = -225;
				gaugeThree.segmentEnd = 45;
				gaugeThree.width = 170;
				gaugeThree.height = 170;
				gaugeThree.needle.imagePath = '/site-media/jgauge/img/jgauge_needle_taco.png';
				gaugeThree.needle.xOffset = 0;
				gaugeThree.needle.yOffset = 0;
                                gaugeThree.label.yOffset = 55;
                                gaugeThree.label.color = '#FFFFFF';
                                gaugeThree.label.precision = 0; // 0 decimals (whole numbers).
				gaugeThree.label.suffix = '%'; // Make the value label watts.
				gaugeThree.ticks.labelRadius = 45;
                                gaugeThree.ticks.labelColor = '#0ce';
                                gaugeThree.ticks.start = 0;
                                gaugeThree.ticks.end = 10;
                                gaugeThree.ticks.count = 5;
                                gaugeThree.ticks.color = 'rgba(0, 0, 0, 0)';
                                gaugeThree.range.color = 'rgba(0, 0, 0, 0)';

